VERSION:
  MAJOR: 0
  MINOR: 5
  BUGFIX: 4
FILEPERM: 0664
DIRPERM: 0777
USE_ETAG: never
USE_MD5: never
USE_LAST_MODIFIED: never
FALLBACK_CACHING_STRATEGY: BabelCache_Filesystem
RELOGINDELAY: 2
START_PAGE: structure
MEDIAPOOL:
  BLOCKED_EXTENSIONS: [.php, .php3, .php4, .php5, .php6, .phtml, .pl, .asp, .aspx, .cfm, .jsp, .htaccess]
ASSETS_CACHE_CONTROL: 'max-age=29030401'
ASSETS_DIRECTORIES:
  - assets
  - sally/data/mediapool
  - sally/data/dyn/public
  - sally/backend/assets/
